# Generated by Django 6.0.2 on 2026-03-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('capabilities', models.JSONField()),
                ('endpoint_url', models.URLField()),
                ('status', models.CharField(default='active', max_length=20)),
            ],
        ),
    ]
